tasks:
  - init: npm ci && npm run build
    command: npm run start

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - jkillian.custom-local-formatters
    - hbenl.vscode-mocha-test-adapter
    - hbenl.vscode-test-explorer
    - hbenl.test-adapter-converter
