language: node_js
install: npm install
sudo: required
addons:
  chrome: stable
  firefox: latest
node_js:
  - "node"
script:
  - npm test
  - FIREFOX_HEADLESS=1 CHROME_HEADLESS=1 npm run karma
  - npm run build
  - npm install codecov -g
after_success:
  - codecov -f coverage/*.json
branches:
  except:
    - /.*-wip$/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org
  keep-history: true
  on:
    branch: master
