name: TTime3 Workflow

on:
  push:
    branches: [master]
  pull_request:

env:
  NODE_VERSION: 16.x

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Run base tests
        run: npm test
      - name: Run browser-based tests
        run: FIREFOX_HEADLESS=1 CHROME_HEADLESS=1 npm run karma
      - uses: codecov/codecov-action@v1
        with:
          files: coverage/*.json

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: [test, e2e]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Github Pages (only on master)
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ["chrome", "firefox"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm install
      - env:
          TESTCAFE_BROWSER_LIST: ${{ matrix.browser }}:headless
          TESTCAFE_VIDEO_DIR: testcafe_video
        run: npm run test:e2e
      - uses: actions/upload-artifact@v2
        with:
          name: testcafe_video_${{ matrix.browser }}
          path: testcafe_video
